=== Diego-ballesteros-fdz/Curriculum_DiegoBallesteros/GastroNomada/recetario.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Elemento raÃ­z -->
  <xs:element name="recetario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="receta" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="descripcion" type="xs:string"/>
              <xs:element name="ingredientes">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="ingrediente" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="cantidad" type="xs:string" use="required"/>
                            <xs:attribute name="unidad" type="xs:string" use="optional"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="pasos">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="paso" maxOccurs="unbounded">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:string">
                            <xs:attribute name="orden" type="xs:string" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="tiempo" type="xs:string"/>
              <xs:element name="dificultad" type="xs:string"/>
              <xs:element name="tradicional" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Diego-ballesteros-fdz/Curriculum_DiegoBallesteros/GastroNomada/RecetarioXSD.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-mode href= "./recetario.dtd"?>
<?xml-stylesheet href="recetario.xsl" type="text/xsl"?>
<recetario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="recetario.xsd">
<!-- receta seria nuestro nodo principal-->
  <receta id="r1">
      <nombre>Paella Valenciana</nombre>
      <descripcion>Plato tradicional de arroz típico de la Comunidad Valenciana.</descripcion>
      <ingredientes>
      <!-- he optado por estipular la cantidad y la unidad como atributos obligatorios-->
        <ingrediente cantidad="400" unidad="g">Arroz</ingrediente>
        <ingrediente cantidad="800" unidad="ml">Caldo de pollo</ingrediente>
        <ingrediente cantidad="200" unidad="g">Pollo</ingrediente>
      </ingredientes>
      <pasos>
      <!-- los pasos funcionan mas o menos de la misma forma que los ingredientes, el orden es obligatorio-->
        <paso orden="1">Sofríe el pollo en una paellera.</paso>
        <paso orden="2">Añade el arroz y el caldo.</paso>
        <paso orden="3">Cocina durante 20 minutos.</paso>
      </pasos>
      <tiempo>45 minutos</tiempo>
      <dificultad>Media</dificultad>
      <tradicional>true</tradicional>
  </receta>
  <receta id="r2">
      <nombre>tortilla de patatas</nombre>
      <descripcion>Plato tradicional de España, con patata huevo y cebolla</descripcion>
      <ingredientes>
        <ingrediente cantidad="500" unidad="g">patata</ingrediente>
        <ingrediente cantidad="300" unidad="ml">aceite</ingrediente>
        <ingrediente cantidad="50" unidad="g">cebolla</ingrediente>
        <ingrediente cantidad="6" unidad="unds">huevo</ingrediente>
      </ingredientes>
      <pasos>
        <paso orden="1">Sofríe las patatas junto a la cebolla</paso>
        <paso orden="2">bate los huevos y vuelca el sofrito sin aceite.</paso>
        <paso orden="3">volcar a una sarten muy caliente</paso>
        <paso orden="4">dar la vuelta y listo</paso>
      </pasos>
      <tiempo>60 minutoss</tiempo>
      <dificultad>Media-baja</dificultad>
      <tradicional>true</tradicional>
  </receta>
</recetario>
